#!/bin/bash

apt-get update
apt-get upgrade

apt-get install nginx
apt-get install mysql-server-5.6
apt-get install php5 php5-cli php5-mysql unzip curl openssl php5-mcrypt 

curl -sS https://getcomposer.org/installer | php
sudo mv composer.phar /usr/local/bin/composer

# Your IP
ip addr show eth0 | grep inet | awk '{ print $2; }' | sed 's/\/.*$//'
